using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OpenBudgeteer.Extensions.MetaData.Migrations
{
    /// <inheritdoc />
    public partial class AutoGeneratedGroup : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "BucketGroup",
                columns: ["BucketGroupId", "Name", "Position"],
                values: [Guid.Parse("00000000-0000-0000-0000-000000000005"), "Auto-Generated", 999]);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "BucketGroup",
                keyColumn: "BucketGroupId",
                keyValue: Guid.Parse("00000000-0000-0000-0000-000000000005"));
        }
    }
}
