name: Docker Image (latest)

on:
  push:
    branches: [ master ]

env:
  DOTNET_VERSION: '6.0' # The .NET SDK version to use

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Test Cases
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Install Blazor dependencies
        run: dotnet restore OpenBudgeteer.Blazor
        
      - name: Build Blazor
        run: dotnet build OpenBudgeteer.Blazor --configuration Release --no-restore
        
      - name: Run Core Test Cases
        run: dotnet test OpenBudgeteer.Core.Test
  deploy-docker:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    needs: test
    if: success()
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: axelander/openbudgeteer:latest
          file: OpenBudgeteer.Blazor/Dockerfile
          platforms: linux/arm64,linux/amd64
        