name: Docker Image CI on pre-release

on:
  push:
    branches: [ pre-release ]
    
env:
  DOTNET_VERSION: '6.0' # The .NET SDK version to use

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Install Blazor dependencies
        run: dotnet restore OpenBudgeteer.Blazor
        
      - name: Build Blazor
        run: dotnet build OpenBudgeteer.Blazor --configuration Release --no-restore
        
      - name: Run Core Test Cases
        run: dotnet test OpenBudgeteer.Core.Test
          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build Docker image
        run: docker build . -t "axelander/openbudgeteer:pre-release" -f "OpenBudgeteer.Blazor/Dockerfile"
        
      - name: Push Docker image
        run: docker push axelander/openbudgeteer:pre-release
